name: Documentation
on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Zensical
        uses: zensical/zensical-action@v1 # Official action

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
